// Bundles the site's fonts and integration logos, and the facts the showreel
// states, into src/assets.js so that the page is self-contained and works
// straight from file://.
import {readFileSync, writeFileSync} from 'fs';
import {dirname, join} from 'path';
import {fileURLToPath} from 'url';
import {getFacts} from './facts.mjs';

const dir = dirname(fileURLToPath(import.meta.url));
const site = join(dir, '../../site');

export const buildAssets = (facts = getFacts()) => {
  const fonts = {
    inter: readFileSync(join(site, 'fonts/inter.woff2')).toString('base64'),
    inconsolata: readFileSync(join(site, 'fonts/inconsolata.woff2')).toString(
      'base64',
    ),
  };
  const logos = Object.fromEntries(
    facts.friends.map(({logo}) => [
      logo,
      readFileSync(join(site, `extras/${logo}.svg`), 'utf8'),
    ]),
  );
  // The wordmark glyphs are the fourth path in the site's logotype.
  const logotype = readFileSync(join(site, 'extras/logotype.svg'), 'utf8');
  const wordmark = [...logotype.matchAll(/<path[^>]*?d="([^"]+)"/gs)][3][1]
    .replace(/\s+/g, ' ')
    .trim();
  const out = join(dir, 'src/assets.js');
  writeFileSync(
    out,
    '// Generated by build-assets.mjs - do not edit.\nwindow.ASSETS = ' +
      JSON.stringify({fonts, logos, wordmark, facts}) +
      ';\n',
  );
  return out;
};

if (process.argv[1] == fileURLToPath(import.meta.url)) {
  console.log('Wrote', buildAssets());
}
