blank_issues_enabled: false
contact_links:
  - name: 🤔 Feature Requests & Questions 
    url: https://github.com/tinyplex/tinybase/discussions
    about: Please ask and answer questions here.
  - name: 💬 New Updates (Bluesky)
    url: https://bsky.app/profile/tinybase.bsky.social
    about: Link to our Bluesky account if you want to follow us and stay up to date with news
  - name: 💬 New Updates (X)
    url: https://x.com/tinybasejs
    about: Link to our X account
  - name: 💬 New Updates (Website)
    url: https://tinybase.org
    about: Link to our official website and documentation
  # - name: 💬 Community Chat {Discord, Slack etc..} Channel 
  #   url: ...