name: ci

on:
  pull_request:
  push:
    branches:
      - beta
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm run compileForTest
      - run: npm run lint
      - run: npm run spell
      - run: npm run ts
      - run: npm run testUnitFast
